# Based on https://github.com/edzer/sfr/blob/master/.travis.yml and https://docs.travis-ci.com/user/languages/r/
#
# See also https://docs.travis-ci.com/user/languages/r and https://github.com/hadley/devtools/blob/master/.travis.yml
# For a potential alternative configuration see https://github.com/metacran/r-builder

language: r
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libapparmor-dev
  - Rscript -e 'update.packages(ask = FALSE)' # https://github.com/travis-ci/travis-ci/issues/6850

warnings_are_errors: true

services:
  - docker

r_packages:
  - rgdal
  - roxygen2
  - covr
  - rjson
  - stringr
  - futile.logger
  - lintr
  - testthat
  - codetools
  - sp
  - gstat
  - proj4
  - devtools
  - units
  - sf
  - fortunes

r_github_packages:
  - r-hub/sysreqs
  - wch/harbor

after_failure:
  - Rscript -e 'library(methods)' -e 'devtools::test()'

after_success:
#  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - echo $TRAVIS_R_VERSION
  - echo $TRAVIS_OS_NAME
